POST http://localhost:9999/payments HTTP/1.1
Content-Type: application/json

{
    "correlationId": "{{$guid}}",
    "amount": 19.90
}
###
POST http://localhost:9999/purge-payments HTTP/1.1
Content-Type: application/json

###

GET http://localhost:9999/payments-summary HTTP/1.1
Content-Type: application/json

###

GET http://localhost:9999/payments-summary?from=2025-08-03T01:41:36.355Z&to=2025-08-03T23:42:46.355Z HTTP/1.1
Content-Type: application/json
