services:
    app1:
        # image: joaogsbittencourt/rinha-de-backend-2025-php:1.5
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        networks:
            - rinha
            - payment-processor
        deploy:
            resources:
                limits:
                    cpus: "0.25"
                    memory: "25MB"
    app2:
        # image: joaogsbittencourt/rinha-de-backend-2025-php:1.5
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        networks:
            - rinha
            - payment-processor
        deploy:
            resources:
                limits:
                    cpus: "0.25"
                    memory: "25MB"

    app3:
        # image: joaogsbittencourt/rinha-de-backend-2025-php:1.5
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        networks:
            - rinha
            - payment-processor
        volumes:
            - ./src/index.php:/var/www/index.php
        deploy:
            resources:
                limits:
                    cpus: "0.25"
                    memory: "25MB"

    nginx:      
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "9999:80"
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - rinha
        depends_on:
            - app1
            - app2
        deploy:
            resources:
                limits:
                    cpus: "0.20"
                    memory: "30MB"

    redis:
        image: redis:7.2-alpine
        command: redis-server --save "" --appendonly no --maxclients 20000
        hostname: redis
        networks:
            - rinha
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 5s
            retries: 5
        deploy:
            resources:
                limits:
                    cpus: "0.55"
                    memory: "245MB"
        
# Redes
networks:
    rinha:
        driver: bridge
    payment-processor:
        external: true
